version: '2'
services:
    fiestareasonerengine-app:
        image: fiestareasonerengine
        external_links:
            - fiestareasonerengine-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fiestareasonerengine?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JBOOTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fiestareasonerengine-mysql:
        extends:
            file: mysql.yml
            service: fiestareasonerengine-mysql
