version: '2'
services:
    fiestareasonerengine-mysql:
        container_name: fiestareasonerengine-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jbooter/FiestaReasonerEngine/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=fiestareasonerengine
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
